### PR TITLE
Update PMTObserver for latest PMT changes

### PR DESCRIPTION
**Pull request by csbnw**
The Python interface of PMT has changed, the `PMTObserver` has been updated accordingly. The new `nvidia` backend is used instead of `nvml`.

### CODE REVIEW

**Comment by csbnw** [comment]
The current PMT Python interface could be improved, e.g. instead of:
```
measured_energy = pmt.pypmt.PMT.joules(begin_state, end_state)
measured_power = pmt.pypmt.PMT.watts(begin_state, end_state)
```
I would like to have:
```
pm = pmt.create("nvidia")
measured_energy = pm.joules(begin_state, end_state)
measured_power = pm.watts(begin_state, end_state)
```
At least, the redundant `pypmt` namespace should be removed.

**Comment by csbnw** [comment]
The code has been updated to work with the latest PMT changes, see this MR: https://git.astron.nl/RD/pmt/-/merge_requests/71

**Comment by csbnw** [comment]
> I would like to have:
> 
> ```
> pm = pmt.create("nvidia")
> measured_energy = pm.joules(begin_state, end_state)
> measured_power = pm.watts(begin_state, end_state)
> ```
Since `joules` and `watts` are static functions of the `PMT` class, this does not work. Instead, `joules` and `watts` functions have been added to the `pmt` namespace of the Python bindings.

**Comment by benvanwerkhoven** [comment]
Great work! I have tested the PMTObserver on the DAS6 Astron and everything worked!

**Pull request merged**
