### PR TITLE
Add support for passing cupy arrays to "C" lang

### LINKED ISSUE #224: Passing cupy arrays to the compiler backend
In a project that I'm working on, it would be useful to be able to create the arrays with cupy and then pass them to the C++ code (that contains a mix of cuda library, e.g. cufft, calls and custom kernels). Is this a feature that is of interest? I got it to work locally, so I could make a pull request if you're interested.

At the moment, this fails on this check and missing support further on in the same function:
https://github.com/KernelTuner/kernel_tuner/blob/08fb58eed26b12fd8da5235298308e2e4e019ede/kernel_tuner/backends/compiler.py#L115

### PR DESCRIPTION
**Pull request by bouweandela**
Add support for passing cupy arrays to "C" lang compiler.

Closes #224

### CODE REVIEW

**Comment by bouweandela** [comment]
I'm not entirely sure where to update the documentation and examples. I think e.g. this example
https://github.com/bouweandela/kernel_tuner/blob/4719acdf4ff096a6e9586e0148c6a9753335393d/examples/cuda/convolution_streams.py#L22-L23
could be simplified by using [cupyx.zeros_pinned](https://github.com/bouweandela/kernel_tuner/blob/4719acdf4ff096a6e9586e0148c6a9753335393d/examples/cuda/convolution_streams.py#L22-L23) to allocate the memory. Please let me know if I missed anything.

**Comment by benvanwerkhoven** [comment]
Thanks a lot for your work on this Bouwe!

I think actually the Point-in-Polygon example might be easier to adapt:
https://github.com/kerneltuner/kernel_tuner/blob/master/examples/cuda/pnpoly.py
The current example uses PyCUDA and indeed passes a GPU memory allocated created using PyCUDA to the Compiler backend. So you could create a variant of that using CuPy instead of PyCUDA, now that you've made this possible. The advantage of only changing the point-in-polygon example is that you don't need to change the CUDA code.

For the time being, I think it's fine to just copy the old example to a new file and call this pnpoly_cupy.py. Perhaps at some point we should consider grouping examples into directories by what backend they are using.

**Comment by bouweandela** [comment]
> For the time being, I think it's fine to just copy the old example to a new file and call this pnpoly_cupy.py.

Done in 303ef3a

**Comment by benvanwerkhoven** [comment]
Thanks a lot @bouweandela ! I've extensively tested everything in this pull request, it all seems to work perfectly!

**Pull request merged**
