### PR TITLE
NVIDIA CUDA Python backend

### PR DESCRIPTION
**Pull request by isazi**
This pull requests adds another backend to kernel tuner, the official Python API provided by NVIDIA.
The pull request fixes issue #144.

### CODE REVIEW

**Comment by isazi** [comment]
I'll fix the bug identified by sonarcloud then.

**Comment by benvanwerkhoven** [comment]
The bug Sonarcloud complains about now is already fixed in master. If you merge master into this branch it should be fixed.

**Comment by benvanwerkhoven** [comment]
Sorry about the close/reopen, I misclicked.

**Comment by isazi** [comment]
All tests passing on DAS-6 using the A6000 GPU and CUDA 11.7, also tried to use `lang="nvcuda"` in the examples and everything works, except for `convolution_correct.py` that I still cannot debug.

**Comment by benvanwerkhoven** [comment]
Thanks a lot for all the work on this Alessio! I'll merge the pull request right now

**Pull request merged**
