### PR TITLE
Refactor interfaces

### PR DESCRIPTION
**Pull request by isazi**
With this pull request we want to structurally, at least at first, refactor some of KT's code to allow developers of components such as observers, strategies, backends, and so on to more easily extend KT.

The discussion for this PL is in issue #177 

As of today the PR is not ready for merging.

### CODE REVIEW

**Comment by isazi** [comment]
Some tests are failing, we need to check them.

**Comment by isazi** [comment]
I'll run a bunch of tests on this branch on the DAS. If everything works I'll run the examples. If this also works, I guess we can merge the pull request back into master.

**Comment by isazi** [comment]
All failing tests are due to Numpy 1.24 not being supported yet. @stijnh is looking into it for future proofing on our side (scikit-learn also needs to support Numpy 1.24, they do not do it properly yet).

**Comment by isazi** [comment]
The examples seem to work fine with this branch, some errors spotted are not directly related to changes here, so I believe this can be merged.
Do @stijnh and @benvanwerkhoven agree?

**Comment by benvanwerkhoven** [comment]
I agree!

**Comment by stijnh** [comment]
Looks good to me!

**Pull request merged**
